name: RustAutoRelease

on:
  release:
    types: [created]


jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
    - uses: actions/checkout@v3
    - run: echo $PWD
    - name: Compile
      id: compile
      uses: rust-build/rust-build.action@v1.4.4
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        # Output target
        RUSTTARGET: ${{matrix.target}}
        # List of extra files to include in build
        # Path to directory containing Cargo.toml (defaults to project root)
        SRC_DIR: feishu_table_client

      