name: RustAutoRelease

on:
  release:
    types: [created]


jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz tar.zst
    steps:

    - name: Get version
      id: get_version
      run: echo "{VERSION}={GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - run: echo $PWD
    - name: Compile
      id: compile
      uses: rust-build/rust-build.action@v1.4.4
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        # Output target
        RUSTTARGET: ${{matrix.target}}
        ARCHIVE_TYPES: ${{ matrix.archive }}
        ARCHIVE_NAME: feishu_table_client_${{steps.get_version.outputs.VERSION}}_${{ matrix.archive }}
        # List of extra files to include in build
        # Path to directory containing Cargo.toml (defaults to project root)
        SRC_DIR: feishu_table_client

      